"""initial schema

Revision ID: 747d56ea4efc
Revises: 
Create Date: 2026-09-22 01:17:49.507372
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '747d56ea4efc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constants',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constants_key'), 'constants', ['key'], unique=True)
    op.create_table('edinitsy',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('short_name', sa.String(length=5), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kontragenty',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=65), nullable=True),
    sa.Column('vid', sa.String(length=10), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('okpo', sa.String(length=10), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('actual_address', sa.String(length=255), nullable=True),
    sa.Column('phones', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kontragenty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_kontragenty_name'), 'kontragenty', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sklady',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sotrudniki',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stavki_nds',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valyuty',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valyuty_code'), 'valyuty', ['code'], unique=True)
    op.create_table('currency_rates',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('multiplicity', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['valyuty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'on_date', name='uq_rate_currency_date')
    )
    op.create_table('dogovory',
    sa.Column('kontragent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('payment_term_days', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kontragent_id'], ['kontragenty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmy',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=65), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('currency_buh_id', sa.Integer(), nullable=True),
    sa.Column('currency_upr_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_buh_id'], ['valyuty.id'], ),
    sa.ForeignKeyConstraint(['currency_upr_id'], ['valyuty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kassy',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['valyuty.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['sotrudniki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenklatura',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=65), nullable=True),
    sa.Column('vid', sa.String(length=20), nullable=False),
    sa.Column('artikul', sa.String(length=20), nullable=True),
    sa.Column('base_unit_id', sa.Integer(), nullable=True),
    sa.Column('main_unit_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_weighted', sa.Boolean(), nullable=False),
    sa.Column('barcode', sa.String(length=13), nullable=True),
    sa.Column('nds_rate_id', sa.Integer(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_unit_id'], ['edinitsy.id'], ),
    sa.ForeignKeyConstraint(['main_unit_id'], ['edinitsy.id'], ),
    sa.ForeignKeyConstraint(['nds_rate_id'], ['stavki_nds.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nomenklatura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_nomenklatura_name'), 'nomenklatura', ['name'], unique=False)
    op.create_table('raschetnye_scheta',
    sa.Column('kontragent_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('bik', sa.String(length=12), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kontragent_id'], ['kontragenty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipy_tsen',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('includes_nds', sa.Boolean(), nullable=False),
    sa.Column('markup_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['valyuty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('documents',
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('subtype', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('kontragent_id', sa.Integer(), nullable=True),
    sa.Column('dogovor_id', sa.Integer(), nullable=True),
    sa.Column('sklad_id', sa.Integer(), nullable=True),
    sa.Column('sklad_to_id', sa.Integer(), nullable=True),
    sa.Column('kassa_id', sa.Integer(), nullable=True),
    sa.Column('valyuta_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('nds_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dogovor_id'], ['dogovory.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmy.id'], ),
    sa.ForeignKeyConstraint(['kassa_id'], ['kassy.id'], ),
    sa.ForeignKeyConstraint(['kontragent_id'], ['kontragenty.id'], ),
    sa.ForeignKeyConstraint(['sklad_id'], ['sklady.id'], ),
    sa.ForeignKeyConstraint(['sklad_to_id'], ['sklady.id'], ),
    sa.ForeignKeyConstraint(['valyuta_id'], ['valyuty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_date'), 'documents', ['date'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_number'), 'documents', ['number'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('tseny_nomenklatury',
    sa.Column('nomenklatura_id', sa.Integer(), nullable=False),
    sa.Column('tip_tsen_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nomenklatura_id'], ['nomenklatura.id'], ),
    sa.ForeignKeyConstraint(['tip_tsen_id'], ['tipy_tsen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_items',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('nomenklatura_id', sa.Integer(), nullable=False),
    sa.Column('sklad_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('nds_rate_id', sa.Integer(), nullable=True),
    sa.Column('nds_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['nds_rate_id'], ['stavki_nds.id'], ),
    sa.ForeignKeyConstraint(['nomenklatura_id'], ['nomenklatura.id'], ),
    sa.ForeignKeyConstraint(['sklad_id'], ['sklady.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_items_document_id'), 'document_items', ['document_id'], unique=False)
    op.create_table('money_movements',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kassa_id', sa.Integer(), nullable=True),
    sa.Column('kontragent_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['kassa_id'], ['kassy.id'], ),
    sa.ForeignKeyConstraint(['kontragent_id'], ['kontragenty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_movements_date'), 'money_movements', ['date'], unique=False)
    op.create_index(op.f('ix_money_movements_document_id'), 'money_movements', ['document_id'], unique=False)
    op.create_table('settlement_movements',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kontragent_id', sa.Integer(), nullable=False),
    sa.Column('dogovor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['dogovor_id'], ['dogovory.id'], ),
    sa.ForeignKeyConstraint(['kontragent_id'], ['kontragenty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_movements_date'), 'settlement_movements', ['date'], unique=False)
    op.create_index(op.f('ix_settlement_movements_document_id'), 'settlement_movements', ['document_id'], unique=False)
    op.create_index(op.f('ix_settlement_movements_kontragent_id'), 'settlement_movements', ['kontragent_id'], unique=False)
    op.create_table('stock_batches',
    sa.Column('nomenklatura_id', sa.Integer(), nullable=False),
    sa.Column('sklad_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['nomenklatura_id'], ['nomenklatura.id'], ),
    sa.ForeignKeyConstraint(['sklad_id'], ['sklady.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_batches_nomenklatura_id'), 'stock_batches', ['nomenklatura_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_sklad_id'), 'stock_batches', ['sklad_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nomenklatura_id', sa.Integer(), nullable=False),
    sa.Column('sklad_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['nomenklatura_id'], ['nomenklatura.id'], ),
    sa.ForeignKeyConstraint(['sklad_id'], ['sklady.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_date'), 'stock_movements', ['date'], unique=False)
    op.create_index(op.f('ix_stock_movements_document_id'), 'stock_movements', ['document_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_nomenklatura_id'), 'stock_movements', ['nomenklatura_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_sklad_id'), 'stock_movements', ['sklad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_sklad_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_nomenklatura_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_document_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_date'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_batches_sklad_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_nomenklatura_id'), table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_index(op.f('ix_settlement_movements_kontragent_id'), table_name='settlement_movements')
    op.drop_index(op.f('ix_settlement_movements_document_id'), table_name='settlement_movements')
    op.drop_index(op.f('ix_settlement_movements_date'), table_name='settlement_movements')
    op.drop_table('settlement_movements')
    op.drop_index(op.f('ix_money_movements_document_id'), table_name='money_movements')
    op.drop_index(op.f('ix_money_movements_date'), table_name='money_movements')
    op.drop_table('money_movements')
    op.drop_index(op.f('ix_document_items_document_id'), table_name='document_items')
    op.drop_table('document_items')
    op.drop_table('tseny_nomenklatury')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('tipy_tsen')
    op.drop_table('raschetnye_scheta')
    op.drop_index(op.f('ix_nomenklatura_name'), table_name='nomenklatura')
    op.drop_table('nomenklatura')
    op.drop_table('kassy')
    op.drop_table('firmy')
    op.drop_table('dogovory')
    op.drop_table('currency_rates')
    op.drop_index(op.f('ix_valyuty_code'), table_name='valyuty')
    op.drop_table('valyuty')
    op.drop_table('stavki_nds')
    op.drop_table('sotrudniki')
    op.drop_table('sklady')
    op.drop_table('roles')
    op.drop_index(op.f('ix_kontragenty_name'), table_name='kontragenty')
    op.drop_table('kontragenty')
    op.drop_table('edinitsy')
    op.drop_index(op.f('ix_constants_key'), table_name='constants')
    op.drop_table('constants')
    # ### end Alembic commands ###
